import Navigation from "@/components/Navigation";
import { useRouter } from "next/router";
import React from "react";
import Head from "next/head";
import styles from "../../styles/postcontact.module.css";
useRouter;
const article = () => {
  const router = useRouter();

  console.log(router);
  console.log(router.route);
  console.log(router.asPath);
  console.log(router.query);

  const buttonFunction = () => {
    router.push("/");
  };
  return (
    <>
      <Head>
        <title>{router.query.slug}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <div className={styles.container_contact}>
        <h1>{router.query.slug}</h1>
        <button onClick={buttonFunction}>Click pour l'accueil</button>
      </div>
    </>
  );
};

export default article;
