import Navigation from "@/components/Navigation";
import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../../styles/postcontact.module.css";
import React from "react";
useRouter;
const article = () => {
  const router = useRouter();
  console.log("************router*****");
  console.log(router);
  console.log("************route*****");
  console.log(router.route);
  console.log("************asPath*****");
  console.log(router.asPath);
  console.log("************query*****");
  console.log(router.query);
  console.log("***********fin*****");
  const pushFunction = () => {
    router.push("/");
  };
  return (
    <>
      <Head>
        <title>Tout les articles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <div className={styles.container_contact}>
        <h1> Création d'un router pour voir ou nous sommes</h1>
        <button onClick={pushFunction}>Push à l'accueil</button>
      </div>
    </>
  );
};

export default article;
