import React from "react";
import styles from "../../styles/postcontact.module.css";
import Head from "next/head";
import { useRouter } from "next/router";
//https://kaamelott.chaudie.re/api/all
export async function getStaticProps() {
  const kamelot = await fetch("https://kaamelott.chaudie.re/api/all");

  const data = await kamelot.json();

  return {
    props: data,

    revalidate: 2,
  };
}

const Contact = (props) => {
  const router = useRouter();

  console.log("**********props**");
  console.log(props.citation[2].infos);
  console.log("**********props**");
  return (
    <>
      <Head>
        <title>contact dans pour les posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container_contact}>
        <h1>Coucou de contact.js dans posts</h1>
        <h2 className={styles.h2_router_aspath}>
          http://localhost:{router.asPath}
        </h2>
        <h2>Incremental Static Regeneration - Data Fetching </h2>

        {/**  // auteur: "Alexandre Astier",
        // acteur: "Vanessa Guedj",
        // personnage: "Angharad",
        // saison: "Pilote",
        // episode: "Le Duel" */}
        <p className={styles.contact_p_citaion_random}>
          {props.citation[2].citation}
        </p>
        <ul className={styles.contact_ul}>
          {props.citation.map((citationss) => (
            <li
              key={citationss.citation}
              className={styles.container_firstPost}
            >
              <p>Acteur: {citationss.infos.acteur}</p>
              <p>Auteur: {citationss.infos.auteur}</p>
              <p>Personnage: {citationss.infos.personnage}</p>
              <p>Saison: {citationss.infos.saison}</p>
              <p>Episode: {citationss.infos.episode}</p>
              <p>Citation: {citationss.citation}</p>
            </li>
          ))}
        </ul>
        {console.log("**********1**")}
        {console.log(props.citation)}
        {console.log("**********2**")}

        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque
          expedita illo deserunt aliquam, aspernatur maxime suscipit a eaque
          voluptate minima et ea, sapiente at ab non assumenda, sed nostrum
          provident! Voluptate reiciendis sunt ratione, consequuntur vitae
          labore culpa, ipsam delectus magni molestias voluptatem totam eligendi
          architecto quia necessitatibus! Voluptas deserunt aliquid molestiae
        </p>
      </div>
    </>
  );
};

export default Contact;
