import Navigation from "@/components/Navigation";
import React from "react";
import styles from "../../styles/first-post.module.css";
import Link from "next/link";
import Head from "next/head";

const FirstPost = () => {
  return (
    <>
      <Head>
        <title>lien vers google</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <div className={styles.container}>
        <h1>Bonjour de posts/first-post</h1>
        <a href="http://google.com" target="_blank">
          ALLER A GOOGLE
        </a>
        <a href="http://localhost:3000" target="_blank">
          ALLER Au SITE LOCALHOST
        </a>
      </div>
    </>
  );
};

export default FirstPost;
