import React, { useEffect, useState } from "react";

import Head from "next/head";
import styles from "../../styles/postcontact.module.css";
import Link from "next/link";
import { useRouter } from "next/router";

const index = ({ posts, date }) => {
  const router = useRouter();
  //a faire si l'on n'utilise pas get static props , il faut enlever le parametre dans index {posts} sinon bug
  //l'avantage avec getStatic>Props c'est que la liste apparait dans le code source pour le seo
  // const [posts, setPosts] = useState([]);
  // useEffect(() => {
  //   const data = fetch("https://jsonplaceholder.typicode.com/posts?_limit=20")
  //     .then((response) => response.json())
  //     .then((data) => {
  //       setPosts(data);
  //     });
  // }, []);
  /////timer pour exemple
  // const [count, setCount] = useState(0);
  // useEffect(() => {
  //   const timer = setInterval(() => setCount((n) => n + 1), 1000);
  //   return () => {
  //     clearInterval(timer);
  //   };
  // }, []);
  return (
    <>
      <Head>
        <title>accueil posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container_contact}>
        <h1>
          Bienvenu sur le dossier posts index.js sans avoir crée une route
        </h1>
        <h2 className={styles.h2_router_aspath}>
          http://localhost:3000{router.asPath}
        </h2>
        <h2> Date du jour : {date}</h2>
        <Link href="/posts/id/10 plats basque">
          <h1 className={styles.h1}>10 plats basque...</h1>
        </Link>
        <Link href="/posts/id/50000 plats basque">
          <h1 className={styles.h1}>50000 plats chinois...</h1>
        </Link>
        {/**     <h2 className={styles.h2}>Timer pour essai : {count}</h2>*/}

        <ul className={styles.post_ul}>
          {console.log(posts)}
          {posts.map((post) => {
            return (
              <li key={post.id}>
                <Link
                  className={styles.link_postsIndex}
                  href={`/posts/${post.id}`}
                >
                  <h1>Article {post.id}</h1>
                  <h2>{post.title}</h2>
                  <p>{post.body}</p>
                </Link>
              </li>
            );
          })}
        </ul>
      </div>
    </>
  );
};

export async function getStaticProps() {
  const posts = await fetch(
    "https://jsonplaceholder.typicode.com/posts?_limit=20"
  ).then((response) => response.json());

  return {
    props: {
      posts,
      date: new Date().toString(),
    },
    revalidate: 2,
  };
}
export default index;
