import Navigation from "@/components/Navigation";
import React from "react";
import styles from "../styles/postcontact.module.css";
import Head from "next/head";

const Contact = () => {
  return (
    <>
      <Head>
        <title>contacter nous</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <div className={styles.container_contact}>
        <h1>Bienvenu de contact.js dans pages</h1>
      </div>
    </>
  );
};

export default Contact;
