//Context
import React, { useContext, useRef } from "react";
import { UserContext } from "@/Contexts/UserContext";
import styles from "@/styles/dashboard.module.css";
import { useRouter } from "next/router";
import Head from "next/head";
const dashboard = () => {
  //afficher le roouter
  const router = useRouter();
  //utiliser le context
  const { user } = useContext(UserContext);
  //pour lier le formulaire avec ref={} dans les input
  const userNameJson = useRef();
  const userFirstnameJson = useRef();
  const ajoutCodePostale = useRef();
  const handleSubmit = (e) => {
    e.preventDefault();
    const newNameProp = {
      name: userNameJson.current.value,
      firstname: userFirstnameJson.current.value,
      codePostale: ajoutCodePostale.current.value,
    };
    fetch("/api/apiconcept", {
      method: "POST",
      body: JSON.stringify(newNameProp),
      headers: {
        "content-type": "application/json",
      },
    })
      .then((res) => res.json())
      .then((data) => {
        userNameJson.current.value = "";
        userFirstnameJson.current.value = "";
        ajoutCodePostale.current.value = "";

        console.log(data);
      });
  };

  const message1 = <h2>Votre message</h2>;
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.dashboard_container_section}>
        <h1>
          Dashboard = tableau de bord s'affiche que si l'utisateur est identifié
          formulaire lié avec le fichier apiConcept pour l'envoi dans la base de
          donnée
        </h1>
        <h2 className={styles.h2_router_aspath}>
          http://locahost:{router.asPath}
        </h2>
        {user && <h2>Bienvenue sur votre compte</h2>}
        {!user && <h2>Vous devez d'abord vous authentifier.</h2>}
        {/**FORMULAIRE D AJOUT DANS LA DATA USER.JSON */}
        <div className={styles.dashboard_container_form}>
          <form
            onSubmit={handleSubmit}
            className={styles.dashboard_form_container}
          >
            {/**LE NOM */}
            <label htmlFor="ajoutName" className={styles.dashboard_form_label}>
              Ajouter un Nom
            </label>
            <input
              ref={userNameJson}
              type="text"
              name=""
              id="ajoutName"
              className={styles.dashboard_form_input}
            />
            {/**LE Prenom */}
            <label
              htmlFor="ajoutFirstname"
              className={styles.dashboard_form_label}
            >
              Ajouter un Prenom
            </label>
            <input
              ref={userFirstnameJson}
              type="text"
              name=""
              id="ajoutFirstname"
              className={styles.dashboard_form_input}
            />
            {/**code postale */}
            <label
              htmlFor="ajoutCodePostale"
              className={styles.dashboard_form_label}
            >
              Votre code postale
            </label>
            <input
              ref={ajoutCodePostale}
              type="text"
              name=""
              id="ajoutCodePostale"
              className={styles.dashboard_form_input}
            />
            <button className={styles.dashboard_form_button}>Ajouter</button>
            {message1}
          </form>
        </div>
        {/**FIN FORM */}
      </section>
    </>
  );
};

export default dashboard;
