import Head from "next/head";
import Link from "next/link";
import styles from "@/styles/postcontact.module.css";
import Navigation from "@/components/Navigation";
import img4 from "../public/assets/img4.jpg";
export async function getStaticProps() {
  const posts = await fetch(
    "https://jsonplaceholder.typicode.com/posts?_limit=20"
  ).then((response) => response.json());

  return {
    props: {
      posts,
    },
  };
}
export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>next apprentissage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main className={styles.container_contact}>
        <section>
          <h1>Pages accueil index</h1>
          <img src="/assets/img4.jpg" />
        </section>

        <ul className={styles.post_ul}>
          {posts.map((post) => {
            return (
              <li key={post.id}>
                <Link
                  className={styles.link_postsIndex}
                  href={`/posts/${post.id}`}
                >
                  <h1>
                    {post.id} - {post.title}
                  </h1>
                  <h2>{post.title}</h2>
                  <p>{post.body}</p>
                </Link>
              </li>
            );
          })}
        </ul>
      </main>
    </>
  );
}
